branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda installdeps .
  - panda-build
script:
  - PERL6LIB=blib/lib prove -v -r --exec=perl6 t/
